In [1]:
import numpy as np

## DataTypes & Attributes

In [3]:
# NumPy's main datatype is ndarray 
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]],
              [[10, 11, 12],
              [13, 14, 15],
              [16, 17, 18]]])

In [6]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [7]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [8]:
a1.shape

(3,)

In [9]:
a2.shape

(2, 3)

In [11]:
a3.shape

(2, 3, 3)

In [12]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [14]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [15]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [16]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [17]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating Arrays

In [18]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [19]:
sample_array.dtype

dtype('int64')

In [26]:
ones = np.ones((2,3), np.int8)

In [29]:
ones

array([[1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [30]:
ones.dtype

dtype('int8')

In [31]:
type(ones)

numpy.ndarray

In [32]:
zeros = np.zeros((2, 3))

In [33]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [35]:
range_array = np.arange(0, 10, 2)

In [36]:
range_array

array([0, 2, 4, 6, 8])

In [38]:
# randint
random_array = np.random.randint(0, 10, size=(3,5))

In [39]:
random_array

array([[5, 7, 1, 3, 5],
       [1, 5, 5, 6, 0],
       [1, 7, 9, 6, 8]])

In [40]:
random_array.size

15

In [41]:
# random.random
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.26471646, 0.37522074, 0.75087442],
       [0.12519417, 0.83878105, 0.09087321],
       [0.46382638, 0.74365117, 0.4784986 ],
       [0.48844376, 0.97460792, 0.66470842],
       [0.69897251, 0.22806427, 0.82745113]])

In [42]:
# random.rand
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.0864391 , 0.8000612 , 0.69060446],
       [0.92464705, 0.17295927, 0.20975904],
       [0.28438271, 0.39660108, 0.69662988],
       [0.72728952, 0.0203264 , 0.69917627],
       [0.42812148, 0.24358155, 0.4286741 ]])

In [55]:
# Psuedo-random numbers
np.random.seed(0)

random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])